### ISSUE TITLE
error in execution of query without results to fetch

### ISSUE THREAD

**Issue by tommasinigiovanni** [rtshome/ansible_pgsql#3]
If Ii use the **postgresql_query** with a query without results to fetch (like an ALTER TABLE to create a new column or an UPDATE) I recieved this error
`FAILED! => {"changed": false, "msg": "database error: the query did not produce any resultset, no results to fetch"}`
is it correct or I'm in wrong?
thanks

**Comment by rtshome** [comment]
You should use the postgresql_command module and not the query module

**Comment by tommasinigiovanni** [comment]
ook, thank's a lot and sorry for the trouble
