### ISSUE TITLE
consider submitting to ansible core?

### ISSUE THREAD

**Issue by aoyawale** [rtshome/ansible_pgsql#4]
saw that you have some modules that are not part of ansible core. Have you considered submitting PR's for those? I do see a lot of folks trying to do queries with ansible.

**Comment by rtshome** [comment]
Hi Jonathan. Why not? :-) All I need to do is submit a PR or is there some guidelines I have to follow prior to submit the PR to main Ansible Repo?

**Comment by aoyawale** [comment]
hello. make sure are following http://docs.ansible.com/ansible/latest/dev_guide/index.html and submit a PR.

**Comment by j-carl** [comment]
Please submit these modules to ansible core. They're very useful.
